config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :lects do 
    resources :comments
  end
resources :lects do 
   member do
     put "like" => "lects#like"
      put "unlike" => "lects#dislike"
   end
  end 
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

   root 'courses#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :lect
  validates :comment_content , :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
before_action :authenticate_user!
def create
  @lect = Lect.find(params[:lect_id])
  @comment = @lect.comments.create(comment_params)
  @comment.user_id = current_user.id 
  if @comment.save
    redirect_to @lect
  else
    flash[:danger] = "Comment Shouldn't Be Empty"
    redirect_to @lect
  end
end
  private

    def comment_params
      params.require(:comment).permit(:comment_content, :user_id, :lect_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do  %>
    <p>
            <strong>
          Posted <%= time_ago_in_words(comment.created_at) %>
            </strong><br>
            <%= h(comment.comment_content) %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_content %><br>
    <%= f.text_field :comment_content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :lect_id %><br>
    <%= f.text_field :lect_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment content</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><h4><%= comment.comment_content %></h4></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment content:</strong>
  <%= @comment.comment_content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Lect:</strong>
  <%= @comment.lect %>
</p>