config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :lects do 
    resources :comments
  end
resources :lects do 
   member do
     put "like" => "lects#like"
      put "unlike" => "lects#dislike"
   end
  end 
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

   root 'courses#index'

end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
   #before_action :authenticate_user!

	def create

		@course = Course.new(course_params)
		@course.user_id = current_user.id

       respond_to do |format|
	    if @course.save
	        format.html { redirect_to @course }
	        format.json { render :show, status: :created, location: @course }
	      else
	        format.html { render :new }
	        format.json { render json: @course.errors, status: :unprocessable_entity }
	        
	      end
        end
    
  
    end
  private

    def course_params
      params.require(:course).permit(:title, :image, :user_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="container">
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image%><br>
    <%= f.file_field :image  %>
  </div>
  <div class="actions ">
    <%= f.submit :Create_Course ,class:"btn-success"%>
  </div>
<% end %>
</div>

app/views/courses/edit.html.erb
<%if current_user&&@course.user.id==current_user.id%>

<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

<%else%>
	  <div class="alert alert-danger" role="alert">
		You Don't Have Rights To Access This Page !
	  </div>
<% end %>

app/views/courses/index.html.erb
<style >
  body{
    background-image: url("/assets/img/backgrounds/1.jpg");
    background-size: cover ;
    background-repeat: no-repeat;
}

.tr{
  background-color: rgba(255,2000,200,0.4);
}

h4{
  color: white;
  font-weight: bold;
}
</style>

<div class="container">
<h1 class="btn-info">Courses</h1>
<div class="tr">
    <table class="table">
      <thead>
        <tr >
          <th colspan="2" class=" btn-warning"><h4>Title</h4></th>
          <th class=" btn-warning"><h4>created_by</h4></th>
          <th colspan="3" class=" btn-warning"></th>
        </tr>
      </thead>

      <tbody>
        <% @courses.each do |course| %>
          <tr>
            <td><h4><%= course.title %></h4></td>
            <td><img src="<%= course.image %>" width="80" height="80"></td>
            <td><h4><%= course.user.name %></h4></td>
            <td><h4><%= link_to 'Show', course,class:"btn btn-info" %></h4></td>
            <% if current_user &&course.user==current_user%>
              <td><h4><%= link_to 'Edit', edit_course_path(course),class:"btn btn-info" %></h4></td>
              <td><h4><%= link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-danger"%></h4></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
</div>
<br>

app/views/courses/new.html.erb
<h1>New Course</h1>
<%= render 'form' %>


<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<style>
  link_to{
    text-decoration:none;
  }
</style>

<div class="container">
    <table class="table">
    <thead>
        <tr>
          <th  class="btn-info">courses
        <%= link_to 'Back', courses_path,class:"btn btn-info pull-right a" %>
        <% if current_user&& @course.user==current_user&&current_user.access_right=="instructor" %>
              <%= link_to 'Add lecture', new_lect_path ,class:"btn btn-info pull-right a"%> 
        <% end %>
        </th>
        </tr>
    </thead>
    <tbody>
    <tr>
    <td>
        <ul>
              <% @course.lects.each do |lect|%>
                 <li><h3>  <%= link_to lect.title ,lect %></h3></li>
                   <%end%>
        </ul>
    </td> 
     
    </tr>
    </tbody>
    </table>