config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :lects do 
    resources :comments
  end
resources :lects do 
   member do
     put "like" => "lects#like"
      put "unlike" => "lects#dislike"
   end
  end 
  resources :courses
  devise_for :users, controllers: { sessions: "users/sessions" , registrations: "users/registrations" }

   root 'courses#index'

end

app/models/lect.rb
class Lect < ActiveRecord::Base
  validates :content, :title, :presence => true
  belongs_to :user
  belongs_to :course
  has_many :comments ,:dependent=>:delete_all
  acts_as_votable
  mount_uploader :attach, FileUploader
end

app/controllers/lects_controller.rb
class LectsController < InheritedResources::Base
   before_action :authenticate_user!
   before_action :set_lect, only: [:show, :edit, :update, :destroy, :like, :dislike]


	def create

		@lect = Lect.new(lect_params)
		@lect.user_id = current_user.id

       respond_to do |format|
	    if @lect.save
	        format.html { redirect_to @lect}
	        format.json { render :show, status: :created, location: @lect }
	      else
	        format.html { render :new }
	        format.json { render json: @lect.errors, status: :unprocessable_entity }

	      end
        end
    
  
    end

    def like
	    @lect = Lect.find(params[:id])
	    @lect.upvote_from current_user
	    redirect_to lect_path
  end
  
   def dislike
	     @lect = Lect.find(params[:id])
	     @lect.downvote_from current_user
	     redirect_to lect_path
  end
  private

  def set_lect
  	@lect = Lect.find(params[:id])
  end

    def lect_params
      params.require(:lect).permit(:title, :content, :attach, :user_id, :course_id)
    end
end

app/helpers/lects_helper.rb
module LectsHelper
end

app/views/lects/_form.html.erb
<%= form_for(@lect) do |f| %>
  <% if @lect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lect.errors.count, "error") %> prohibited this lect from being saved:</h2>

      <ul>
      <% @lect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :attach %><br>
    <%= f.file_field :attach %>
  </div>

  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.collection_select :course_id, current_user.courses,:id,:title, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lects/edit.html.erb
<%if current_user&&@lect.user.id==current_user.id%>
<h1>Editing Lect</h1>
<%= render 'form' %>

<%= link_to 'Show', @lect %> |
<%= link_to 'Back', :back %>


<%else%>
	  <div class="alert alert-danger" role="alert">
		You Don't Have Rights To Access This Page !
	  </div>
<% end %>

app/views/lects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Attach</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lects.each do |lect| %>
      <tr>
        <td><%= lect.title %></td>
        <td><%= lect.content %></td>
        <td><%= lect.attach %></td>
        <td><%= link_to 'Show', lect %></td>
        <% if current_user&&lect.user==current_user %>
            <td><%= link_to 'Edit', edit_lect_path(lect) %></td>
            <td><%= link_to 'Delete', lect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lects/new.html.erb
<h1>New Lect</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/lects/show.html.erb
<div class="container">

  <%if  flash[:danger] %>
  <div class="alert alert-danger" role="alert">
  <%= flash[:danger] %>
  </div>
  <%end%>
  </p>
  <div class="jumbotron col-md-8 col-md-offset-2">
  <pre>
  <%= @lect.title %>

  <%= @lect.content %>


  Download:<a href="<%= @lect.attach_url %>" download><%= @lect.attach %></a> <% if current_user&&@lect.user==current_user  %>
<h4><%= link_to 'Edit', edit_lect_path(@lect) %>|<%= link_to 'Delete', lects_path %></h4>
     
<% end %></pre>
  <%= link_to like_lect_path(@lect) , method: :put do %>
  <button type="button" class="btn btn-info">
        <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center " > </span>
        <span class="badge"><%= @lect.get_upvotes.size %></span>
  </button>        
 <% end  %>     
 <%= link_to unlike_lect_path(@lect) , method: :put do %>
    <button type="button" class="btn btn-info">
          <span class=" info glyphicon glyphicon-thumbs-down glyphicon-align-center "> </span>
          <span class="badge"><%= @lect.get_downvotes.size %></span>
    </button>
<!--     if disliks becoms 2 , lecture becomes span
 -->    <%if  @lect.get_downvotes.size==1%>
     <% Lect.destroy(@lect.id)%>
      <%end%>
 <% end  %>
 
 <div id="comments">
 <h2><u>Comments</u></h2><br>
    <%= render :partial => @lect.comments %>
 </div><br>

</div>

<div class="col-md-2"></div>

<div class="jumbotron col-md-8 col-md-offset-2">
<h2> Leave comment </h2>
      <%= simple_form_for [@lect ,Comment.new] do |f| %>
       <p>
          <%= f.input :comment_content , as: :text , input_html: { row:"2" } %>
       </p>
       <div class="btn">
           <%= f.submit "Add " , class:'btn btn-info'  %>
           <%end%>
       </div>   

   
   </div> 
    <div class="jumbotron col-md-8 col-md-offset-2">
        <h4><%= link_to 'Back', course_path(@lect.course.id) %></h4>
    </div></div>